version: '3'
services:
  web:
    image: odoo:18.0
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=dpg-csp6ds3v2p9s73bbptmg-a
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=B3cwhuBhVr2TDQUJY6DBQH6sJ2OTcTdU
      - POSTGRES_DB=odoo_35g4
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
